@echo off
REM HealthAI Llama2 Setup Script for Windows
REM This script sets up Llama2 locally using Ollama for the HealthAI platform

echo 🚀 HealthAI Llama2 Setup Script (Windows)
echo ==========================================

REM Check if PowerShell is available
powershell -Command "Write-Host 'PowerShell is available'" >nul 2>&1
if errorlevel 1 (
    echo ❌ PowerShell is required but not available
    pause
    exit /b 1
)

echo 📋 Checking system requirements...

REM Check if curl is available (Windows 10 1803+ has curl built-in)
curl --version >nul 2>&1
if errorlevel 1 (
    echo ❌ curl is required. Please install curl or use Windows 10 version 1803 or later
    echo You can download curl from: https://curl.se/windows/
    pause
    exit /b 1
)

echo ✅ System requirements check passed

REM Check if Ollama is already installed
ollama --version >nul 2>&1
if not errorlevel 1 (
    echo ✅ Ollama is already installed
    ollama --version
    goto :start_service
)

echo 📦 Installing Ollama...
echo ⬇️  Please download and install Ollama from: https://ollama.ai/
echo After installation, please restart this script
echo.
echo Press any key to open the Ollama download page...
pause >nul
start https://ollama.ai/
pause
exit /b 0

:start_service
REM Check if Ollama service is running
tasklist /FI "IMAGENAME eq ollama.exe" 2>NUL | find /I /N "ollama.exe">NUL
if not errorlevel 1 (
    echo ✅ Ollama service is already running
    goto :pull_model
)

echo 🔄 Starting Ollama service...
start /B ollama serve
timeout /t 3 >nul

REM Check if service started
tasklist /FI "IMAGENAME eq ollama.exe" 2>NUL | find /I /N "ollama.exe">NUL
if errorlevel 1 (
    echo ❌ Failed to start Ollama service
    echo Please ensure Ollama is properly installed
    pause
    exit /b 1
)

echo ✅ Ollama service started successfully

:pull_model
echo 🧠 Downloading Llama2 7B model (this may take a while)...
echo This will download approximately 3.8GB of data
ollama pull llama2:7b

if errorlevel 1 (
    echo ❌ Failed to download Llama2 model
    pause
    exit /b 1
)

echo ✅ Llama2 7B model downloaded successfully

REM Test the installation
echo 🧪 Testing Llama2 installation...
powershell -Command "try { $response = Invoke-RestMethod -Uri 'http://localhost:11434/api/generate' -Method Post -ContentType 'application/json' -Body '{\"model\": \"llama2:7b\", \"prompt\": \"Hello, are you working?\", \"stream\": false}'; if ($response.response) { Write-Host '✅ Llama2 is working correctly!' } else { Write-Host '❌ Llama2 test failed' } } catch { Write-Host '❌ Llama2 test failed - service may not be ready' }"

REM Create configuration file
echo ⚙️  Creating configuration file...
if not exist config mkdir config

(
echo // Local Llama2 Configuration
echo // This file is auto-generated by setup-llama2.bat
echo.
echo export const localLlama2Config = {
echo   api: {
echo     local: {
echo       baseUrl: 'http://localhost:11434',
echo       model: 'llama2:7b',
echo       endpoint: '/api/generate',
echo       enabled: true,
echo       tested: true,
echo       installedAt: '%date% %time%'
echo     }
echo   },
echo.  
echo   status: {
echo     installed: true,
echo     model: 'llama2:7b',
echo     service: 'ollama',
echo     platform: 'windows'
echo   }
echo };
echo.
echo // Test function
echo export async function testLocalLlama2() {
echo   try {
echo     const response = await fetch('http://localhost:11434/api/generate', {
echo       method: 'POST',
echo       headers: { 'Content-Type': 'application/json' },
echo       body: JSON.stringify({
echo         model: 'llama2:7b',
echo         prompt: 'Test message',
echo         stream: false
echo       })
echo     });
echo.    
echo     return response.ok;
echo   } catch (error) {
echo     return false;
echo   }
echo }
) > config\llama2.local.js

echo ✅ Configuration file created at config\llama2.local.js

REM Create service management script
echo 🛠️  Creating service management script...
(
echo @echo off
echo REM HealthAI Llama2 Service Management Script for Windows
echo.
echo if "%%1"=="start" goto start
echo if "%%1"=="stop" goto stop
echo if "%%1"=="status" goto status
echo if "%%1"=="test" goto test
echo if "%%1"=="logs" goto logs
echo goto usage
echo.
echo :start
echo echo 🚀 Starting Ollama service...
echo tasklist /FI "IMAGENAME eq ollama.exe" 2^>NUL ^| find /I /N "ollama.exe"^>NUL
echo if not errorlevel 1 ^(
echo     echo ✅ Ollama is already running
echo ^) else ^(
echo     start /B ollama serve
echo     timeout /t 2 ^>nul
echo     tasklist /FI "IMAGENAME eq ollama.exe" 2^>NUL ^| find /I /N "ollama.exe"^>NUL
echo     if not errorlevel 1 ^(
echo         echo ✅ Ollama started successfully
echo     ^) else ^(
echo         echo ❌ Failed to start Ollama
echo     ^)
echo ^)
echo goto end
echo.
echo :stop
echo echo 🛑 Stopping Ollama service...
echo taskkill /F /IM ollama.exe ^>nul 2^>^&1
echo echo ✅ Ollama stopped
echo goto end
echo.
echo :status
echo tasklist /FI "IMAGENAME eq ollama.exe" 2^>NUL ^| find /I /N "ollama.exe"^>NUL
echo if not errorlevel 1 ^(
echo     echo ✅ Ollama is running
echo     echo 📊 Service details:
echo     tasklist /FI "IMAGENAME eq ollama.exe"
echo ^) else ^(
echo     echo ❌ Ollama is not running
echo ^)
echo goto end
echo.
echo :test
echo echo 🧪 Testing Llama2...
echo powershell -Command "try { $response = Invoke-RestMethod -Uri 'http://localhost:11434/api/generate' -Method Post -ContentType 'application/json' -Body '{\"model\": \"llama2:7b\", \"prompt\": \"Hello\", \"stream\": false}'; if ($response.response) { Write-Host '✅ Llama2 is working correctly' } else { Write-Host '❌ Llama2 test failed' } } catch { Write-Host '❌ Llama2 test failed' }"
echo goto end
echo.
echo :logs
echo echo 📋 Ollama logs not available on Windows
echo echo Use Task Manager to monitor Ollama process
echo goto end
echo.
echo :usage
echo echo Usage: %%0 {start^|stop^|status^|test^|logs}
echo echo.
echo echo Commands:
echo echo   start   - Start Ollama service
echo echo   stop    - Stop Ollama service
echo echo   status  - Check service status
echo echo   test    - Test Llama2 functionality
echo echo   logs    - View service logs
echo.
echo :end
) > manage-llama2.bat

echo ✅ Service management script created: manage-llama2.bat

echo.
echo 🎉 Llama2 setup completed successfully!
echo.
echo 📋 Next steps:
echo 1. The HealthAI application will now use Llama2 for AI responses
echo 2. Ollama service is running in the background
echo 3. Use 'manage-llama2.bat status' to check service status
echo 4. Use 'manage-llama2.bat test' to test functionality
echo.
echo 🔧 Service management:
echo • Start service: manage-llama2.bat start
echo • Stop service:  manage-llama2.bat stop
echo • Check status:  manage-llama2.bat status
echo • Test function: manage-llama2.bat test
echo.
echo 📚 Documentation: docs\LLAMA2_INTEGRATION.md
echo.
echo 🚀 You can now start the HealthAI application and enjoy AI-powered health assistance!
echo.
pause

